# Generated by Django 3.1.4 on 2021-01-12 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('limbs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemsupplier',
            name='supplier_part_number',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='tag',
            name='name',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
