# Generated by Django 3.1.2 on 2021-04-20 21:08

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('limbs', '0002_auto_20210112_0117'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('created_date', models.DateField(default=datetime.date.today)),
                ('completed', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='ItemOrder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField()),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='limbs.item')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='limbs.order')),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='limbs.supplier')),
            ],
        ),
    ]
